### ISSUE TITLE
Cannot run NUnit with ReSharper

### ISSUE THREAD

**Issue by tpluscode** [nunit/dotnet-test-nunit#106]
Sorry if this is not the right place to ask. I'm converting a project to project.json and `dotnet test` works fine in console. I updated to R# 2016.3.2 and my tests are discovered in VS. Unfortunately I cannot run them. When I try, no tests are executed and the Unit Test Session window displays an exception stack trace:

```
ERROR System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JetBrains.ReSharper.UnitTestFramework.Launch.Stages.DiscoveryStage.Run(CancellationToken token)
   at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestLaunch.RunStage(Object stageObject)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```

My `project.json` is as follows (relevant parts):

``` json
{
 "dependencies": {
    "NUnit": "3.6.1",
    "dotnet-test-nunit": "3.4.0-*"
  },
  "testRunner": "nunit"
}
```

Is there anything I can try?

**Comment by jnm2** [comment]
This might be https://youtrack.jetbrains.com/issue/RSRP-461908

**Comment by jnm2** [comment]
Wait- you're converting *to* project.json, not *from* project.json?

If you're converting a .NET Framework (not .NET Core) .csproj from packages.config (NuGet v2) to project.json (NuGet v3), 2017.1 EAP 2 is the first version of ReSharper that has worked for me in a long time.

**Comment by tpluscode** [comment]
Unfortunately EAP 3 doesn't work either :(. Same error.

**Comment by jnm2** [comment]
Your project.json looks like you're running .NET Core. Is that correct?
Be aware that project.json's official replacement is being released on the 7th with VS2017's RTM, a new .csproj format for both .NET Core and .NET Framework where no project.json file is used.
