### ISSUE TITLE
Unable to use NUnit Runner with .NET 4.5.2

### ISSUE THREAD

**Issue by jorgebay** [nunit/dotnet-test-nunit#45]
To reproduce it:
```javascript
{
  "version": "1.0.0-*",
  "testRunner": "nunit",
  "dependencies": {
    "MyClassLibrary": { "target": "project" },
    "NUnit": "3.4.0",
    "dotnet-test-nunit": "3.4.0-beta-1"
  },
  "frameworks": {
    "net452":  {}, 
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```
Run:
```
dotnet test test\MyClassLibrary.Tests -f net452
```
Exception:
```
NUnit .NET Core Runner 3.4.0
Copyright (C) 2016 Charlie Poole
Runtime Environment
    OS Platform: Windows
     OS Version: 6.1.7601
        Runtime: win7-x64
Test Files
    C:\path\to\project\bin\Debug\net452\win7-x64\MyClassLibrary.Tests.dll
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateSymReader64(Guid& id, Object& symReader)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateNativeSymReader(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader..ctor(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.PdbReaderFactory.Create(String pdbPath)
   at Microsoft.Extensions.Testing.Abstractions.SourceInformationProvider..ctor(String pdbPath, IPdbReaderFactory pdbReaderFactory)
   at NUnit.Runner.Navigation.NavigationDataProvider.GetNavigationDataProvider(String assemblyPath)
   at NUnit.Runner.TestRunner.Execute()
   at NUnit.Runner.TestRunner.Run(String[] args)
```

YMMV with other runtimes, but you will get similar errors.

**Comment by jasonwilliams200OK** [comment]
Can't reproduce with the following setup:

```powershell
Directory: C:\temp\issue-45
Sub Directories: MyClassLibrary, Test
```

MyClassLibrary\project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {},
  "frameworks": {
    "net45": {},
    "netcoreapp1.0": {
      "dependencies": {
        "System.Collections": "4.0.11",
        "System.IO": "4.1.0",
        "System.Linq": "4.1.0",
        "System.Runtime": "4.1.0",
        "System.Runtime.Extensions": "4.1.0",
        "System.Resources.ResourceManager": "4.0.1"
      }
    }
  }
}
```

MyClassLibrary\SomeClass.cs:


```csharp
using System;

namespace MyLib
{
    public class SomeClass
    {
        public static string GetString()
        {
            return "Hello World";
        }
    }
}
```

Test\project.json:

```json
{
  "version": "1.0.0-*",
  "testRunner": "nunit",
  "dependencies": {
    "MyClassLibrary": { "target": "project" },
    "NUnit": "3.4.0",
    "dotnet-test-nunit": "3.4.0-beta-1"
  },
  "frameworks": {
    "net452":  {}, 
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

Test\Test1.cs:

```csharp
 using MyLib;
 using NUnit.Framework;

 class MainTest
 {
         [Test]
         public void Should_return_something()
         {
             var sample = SomeClass.GetString();
             Assert.NotNull(sample);
         }
}
```

Executed:

```powershell
cd C:\temp\issue-45

dotnet restore

dotnet test Test\ -f net452
```

No errors.

```powershell
C:\temp\issue-45> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

Must be something in your MyClassLibrary which is causing the crash. You may try creating a regular console app around your lib and see if that gets crashed with `dotnet run MyConsoleApp\ -f net452`.

**Comment by jasonwilliams200OK** [comment]
Note that I tested with both `"net45": {},` and `"net45": {},` (i.e. `-f net452` and `-f net45` respectively). Generally, the library can have lower minor and patch number in version than the consumer app.

**Comment by ejball** [comment]
I had the same error. I don't know why, but adding `"buildOptions": { "debugType": "portable" }` to the test project fixed it for me.

**Comment by jasonwilliams200OK** [comment]
@ejball, 

>I had the same error. 

it will really help us differentiating whether it is our issue, your lib issue, or dotnet-cli issue; if you try the steps i described above. Or provide steps to repro to make something actionable for us. See http://sscce.org/

**Comment by ejball** [comment]
I was able to reproduce the error with your exact steps. Only obvious difference is my OS version.

```
PS C:\Temp\issue-45> dotnet restore
log  : Restoring packages for C:\Temp\issue-45\Test\project.json...
log  : Restoring packages for C:\Temp\issue-45\MyClassLibrary\project.json...
log  : Writing lock file to disk. Path: C:\Temp\issue-45\MyClassLibrary\project.lock.json
log  : C:\Temp\issue-45\MyClassLibrary\project.json
log  : Restore completed in 285ms.
log  : Writing lock file to disk. Path: C:\Temp\issue-45\Test\project.lock.json
log  : C:\Temp\issue-45\Test\project.json
log  : Restore completed in 1403ms.
PS C:\Temp\issue-45> dotnet test Test -f net452
Project MyClassLibrary (.NETFramework,Version=v4.5) will be compiled because expected outputs are missing
Compiling MyClassLibrary for .NETFramework,Version=v4.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.7382757
Project Test (.NETFramework,Version=v4.5.2) will be compiled because dependencies changed
Compiling Test for .NETFramework,Version=v4.5.2

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.7864295


NUnit .NET Core Runner 3.4.0
Copyright (C) 2016 Charlie Poole
Runtime Environment
    OS Platform: Windows
     OS Version: 10.0.10240
        Runtime: win10-x64
Test Files
    C:\Temp\issue-45\Test\bin\Debug\net452\win7-x64\Test.dll
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateSymReader64(Guid& id, Object& symReader)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateNativeSymReader(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader..ctor(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.PdbReaderFactory.Create(String pdbPath)
   at Microsoft.Extensions.Testing.Abstractions.SourceInformationProvider..ctor(String pdbPath, IPdbReaderFactory pdbReaderFactory)
   at NUnit.Runner.Navigation.NavigationDataProvider.GetNavigationDataProvider(String assemblyPath)
   at NUnit.Runner.TestRunner.Execute()
   at NUnit.Runner.TestRunner.Run(String[] args)
PS C:\Temp\issue-45> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by jasonwilliams200OK** [comment]
Thanks @ejball, I have made a fix, can you try it out before we merge it in for next release?

```cmd
cd C:\Temp\issue-45 :: assuming you still have it there as is..
git clone https://github.com/nunit/dotnet-test-nunit -b fix/net45 --recursive
```

Then in `Test\project.json`, change:

```json
    "dotnet-test-nunit": "3.4.0-beta-1"
```

to:

```json
    "dotnet-test-nunit": { "target": "project" },
```

and run `dotnet restore && dotnet test Test -f net451`.

**Comment by jasonwilliams200OK** [comment]
@ejball, edited above. I can't reproduce this issue on my system, that's why asking for verification from you. :)

**Comment by ejball** [comment]
@jasonwilliams200OK, I followed your instructions. Confirmed **fixed**.

**Comment by jasonwilliams200OK** [comment]
Thank you!

**Comment by BrainCrumbz** [comment]
Could anyone please explain what was the actual fix, and where was it applied? Thank you

**Comment by rprouse** [comment]
The fixes were made in PR #54

**Comment by BrainCrumbz** [comment]
@rprouse thanks for info. 

Sadly we're trying all sort of sorcery (just by looking at recent commits on our [feat/integrate-vs2015](https://github.com/nspec/DotNetTestNSpec/commits/feat/integrate-vs2015) branch), but when running this on a sample test project (`--debugChannel` mocks socket outgoing messages to console log):

```dos
> dotnet test --designtime --port 99999 --list -- --debugChannel
```

we keep on hitting this again and again, no matter what, both for net452 and netcoreapp1.0:

> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Testing.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by BrainCrumbz** [comment]
After many tests and a lot of googling, found a workaround:

in client test project, take an explicit dependency on `"Microsoft.Extensions.Testing.Abstractions": "1.0.0-preview2-003121",`. It seems a known issue, between .NET Core CLI, Tooling Preview 2 and NuGet, which of course will not be fixed given that it is strictly related to project.json.

After a lot of fiddling (before this workaround), we were able to make it work for .NET Framework target by backporting from net452 to net451. But for .NET Core target, the only way was to add such "transitive" dependency.
